const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const core=require('../src/dashboard/assets/hub_core.js');
function page(){let now=0,drawn=false;const nodes={},intervals=[],scheduled=[];const context={clearRect(){drawn=false},drawImage(){drawn=true}};const element=id=>nodes[id]??={value:id==='source'?'live':'',hidden:true,textContent:'',clientWidth:600,clientHeight:400,parentElement:{clientWidth:600,clientHeight:400},getContext:()=>context,addEventListener(){},replaceChildren(){},appendChild(){}};
 const packet={source:'live',frame_id:'first',frame_width:640,frame_height:480,frame_age_seconds:.2,stale_after_seconds:1,tracks:[],detections:[],jpeg:'YQ==',forecast_status:'AVAILABLE',forecast_horizon_seconds:5};
 const env={HubCore:core,document:{getElementById:element,querySelectorAll:()=>[],addEventListener(){},hidden:false},window:{addEventListener(){}},performance:{now:()=>now},setInterval:f=>intervals.push(f),setTimeout:f=>scheduled.push(f),clearTimeout(){},AbortSignal,Uint8Array,atob,Blob,
 fetch:async()=>({ok:true,status:200,json:async()=>packet}),createImageBitmap:async()=>({close(){}})};vm.createContext(env);vm.runInContext(fs.readFileSync(path.join(__dirname,'../src/dashboard/assets/hub.js'),'utf8'),env);vm.runInContext("source='live';catalog.cameras=[{camera_id:'gate'}]",env);
 return {env,nodes,intervals,setTime:t=>now=t,drawn:()=>drawn,load:()=>vm.runInContext('loadFrame(epoch)',env),run:code=>vm.runInContext(code,env)};
}
test('live image and metrics expire while the next request hangs',async()=>{const p=page();await p.load();assert.ok(p.drawn());p.env.fetch=()=>new Promise(()=>{});p.load();p.setTime(900);p.intervals[0]();assert.equal(p.drawn(),false);assert.equal(p.nodes['metric-ttc'].textContent,'—');assert.match(p.nodes['empty-message'].textContent,/stale/);});
test('late decoded frames are closed and cannot repopulate the scene',async()=>{const p=page();let closed=false;p.env.createImageBitmap=async()=>{p.setTime(1100);return {close(){closed=true}}};await p.load();assert.equal(p.drawn(),false);assert.ok(closed);});
test('source switching rejects an in-flight live response',async()=>{const p=page();let resolve;p.env.fetch=()=>new Promise(r=>resolve=r);const pending=p.load();p.run("epoch++;source='demo'");resolve({ok:true,status:200,json:async()=>({source:'live',stale_after_seconds:1,frame_age_seconds:0})});await pending;assert.equal(p.drawn(),false);});
test('camera setup selects live, empty setup selects demo, missing PPE stays unknown',()=>{assert.equal(core.initial({cameras:[]}),'demo');assert.equal(core.initial({cameras:[{}]}),'live');assert.equal(core.ppe(undefined),'UNKNOWN');assert.equal(core.risk({evaluated_pairs:[]}).probability,null);});

test('missing WebGL does not prevent camera display',async()=>{const p=page();assert.match(p.nodes['webgl-wrapper'].textContent,/3D view unavailable/);await p.load();assert.ok(p.drawn());});
test('hidden pages do not fetch or decode new frames',async()=>{const p=page();let fetched=false;p.env.document.hidden=true;p.env.fetch=async()=>{fetched=true};await p.load();assert.equal(fetched,false);});
